name: spymicmac
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - pyproj
  - scikit-image>=0.18
  - geopandas
  - matplotlib
  - sphinx
  - opencv
  - lxml
  - gdal
  - pyasn1
  - earthengine-api
  - pip
  - pip:
      - llc
      - pybob>0.25
      - pymmaster>0.1
      - sphinx-argparse
      - sphinx-rtd-theme
      - usgs