name: spymicmac
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - scikit-image
  - geopandas
  - geoutils
  - opencv<4.9.0
  - lxml
  - gdal
  - pyasn1
  - numba
  - earthengine-api
  - imagemagick
  - exiftool
  - pillow>9.1.0
  - rtree
  - sphinx
  - sphinx-argparse
  - sphinx-book-theme
  - pip
  - pip:
      - usgs