name: spymicmac
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - pyproj
  - scikit-image>=0.19
  - geopandas
  - matplotlib
  - sphinx
  - opencv
  - lxml
  - gdal
  - pyasn1
  - numba
  - earthengine-api
  - pillow>9.1.0
  - pip
  - pip:
      - llc
      - pybob>=0.25.1
      - pymmaster>=0.1.1
      - sphinx-argparse
      - sphinx-rtd-theme
      - usgs