name: spymicmac
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - scikit-image
  - geopandas
  - geoutils
  - matplotlib
  - sphinx
  - lxml
  - gdal
  - pyasn1
  - numba
  - earthengine-api
  - pillow>9.1.0
  - pip
  - pip:
      - sphinx-argparse
      - sphinx-rtd-theme
      - usgs