"""
spymicmac.preprocessing is a collection of tools for preprocessing images
"""
import os
from pathlib import Path
import argparse
import shutil
import tarfile
import numpy as np
import pandas as pd
from glob import glob
from skimage import io, filters
from spymicmac.image import join_hexagon
from spymicmac.matching import find_reseau_grid, remove_crosses
from spymicmac.resample import resample_hex
from spymicmac import micmac


def initialize_kh9_mc(add_sfs=False, cam_csv='camera_defs.csv', overwrite=False):
    """
    Initialize the following files needed for processing KH-9 MC images, if they do not already exist:

      - MicMac-LocalChantierDescripteur.xml
      - Ori-Init/AutoCal_Foc-304800_KH9MC.xml
      - Ori-InterneScan/MeasuresCamera.xml

    If multiple "cameras" (i.e., images acquired from different missions) are being used, these should be
    defined in a cam_csv file, as generated by micmac.generate_multicam_csv().

    :param bool add_sfs: use SFS to help find tie points in low-contrast images [False]
    :param str cam_csv: the name of the CSV file containing camera information [camera_defs.csv]
    :param bool overwrite: overwrite existing files [False]
    """
    # first, check whether we have multiple cameras
    is_multicam = os.path.exists(cam_csv)

    if is_multicam:
        cameras = pd.read_csv(cam_csv)

        if not os.path.exists('MicMac-LocalChantierDescripteur.xml'):
            micmac.create_localchantier_xml(add_sfs=add_sfs, cam_csv=cam_csv)

        for cam in cameras.itertuples():
            foc = int(cam.focal * 1000)
            if not os.path.exists(Path('Ori-Init', f"AutoCal_Foc-{foc}_{cam.name}.xml")):
                micmac.init_autocal(framesize=(cam.width, cam.height), foc=cam.focal, camname=cam.name)

    else:
        if not os.path.exists(Path('Ori-Init', 'AutoCal_Foc-304800_KH9MC.xml')) or overwrite:
            micmac.init_autocal()

        if not os.path.exists('MicMac-LocalChantierDescripteur.xml') or overwrite:
            micmac.create_localchantier_xml(add_sfs=add_sfs)

    if not os.path.isfile(Path('Ori-InterneScan', 'MeasuresCamera.xml')) or overwrite:
        os.makedirs('Ori-InterneScan', exist_ok=True)
        micmac.generate_measures_files(joined=True)
        shutil.move('MeasuresCamera.xml', 'Ori-InterneScan')


def extract(tar_ext='.tgz'):
    """
    Extract image parts from tar files in the current directory.

    :param str tar_ext: the extension of the files to look for (default: .tgz)
    """
    # make a directory to move the tarballs to
    os.makedirs('tarballs', exist_ok=True)

    tarlist = glob('*' + tar_ext)
    tarlist.sort()

    if len(tarlist) > 0:
        print('Extracting images from tar files.')
        for tarball in tarlist:
            print(tarball)
            with tarfile.open(tarball, 'r') as tfile:
                tfile.extractall('.')
            shutil.move(tarball, 'tarballs')
    else:
        print('No tar files found, skipping.')
        # we still want to make sure that we have a list of images to work with.
        tarlist = list(set([os.path.splitext(fn)[0].split('_')[0] for fn in glob('D*.tif')]))
        tarlist.sort()

    return tarlist


def check_reseau() -> bool:
    """
    Check whether all KH-9 Mapping Camera images in the current directory have a corresponding Measures{fn_img}.xml
    file in Ori-InterneScan.

    :return: True if the files exist; False if they do not exist
    """
    imlist = glob('DZB*.tif')
    measlist = glob('MeasuresIm*.tif.xml', dir_fd='Ori-InterneScan')

    # if there are no DZB*.tif, but there are MeasuresIm files, we've probably done this step
    if len(imlist) == 0 and len(measlist) > 0:
        return True
    else:
        # check that each image file has a matching measuresim file
        return all([any([im in meas for meas in measlist]) for im in imlist])

